### ISSUE TITLE
Identify copyright holder in LICENSE

### ISSUE THREAD

**Issue by botimer** [samvera/hydra-pcdm#253]
The LICENSE file has the ASLv2, but no copyright statement.

**Comment by no-reply** [comment]
See, as an example: https://github.com/samvera/hyrax/blob/master/LICENSE#L192

**Comment by tpendragon** [comment]
This one's hard. The gem was built as part of a multi-institutional sprint. The participating institutions who had early commits were Penn State University, Cornell University, and DCE. The second round of major work had those in addition to Oregon State University, UCSD, and University of Michigan. There's probably some I'm missing too. Maybe we just assign copyright to DCE due to their early work and current product ownership and add the bit about copyright by commit history?
